python matching.py /Users/quake0day/wholedavis3rd_video_short_2_b/path2_12
python matching.py /Users/quake0day/wholedavis3rd_video_short_2_b/path2_4
python matching.py /Users/quake0day/wholedavis3rd_video_short_2_b/path2_18
python matching.py /Users/quake0day/wholedavis3rd_video_short_2_b/path2_9
python matching.py /Users/quake0day/wholedavis3rd_video_short_2_b/path2_54
python matching.py /Users/quake0day/wholedavis3rd_video_short_2_b/path2_5
python matching.py /Users/quake0day/wholedavis3rd_video_short_2_b/path2_7
python matching.py /Users/quake0day/wholedavis3rd_video_short_2_b/path2_46
python matching.py /Users/quake0day/wholedavis3rd_video_short_2_b/path2_35
python matching.py /Users/quake0day/wholedavis3rd_video_short_2_b/path2_25